#%RAML 1.0
title: SFTPexo1

types:
  Invoice: !include types/Invoices.raml

/invoices:
  get:
    queryParameters:
      currency:
        type: string
        required: false
        enum: [USD, EUR]
    responses:
      200:
        body:
          application/json:
            type: Invoice[]
      400:
        body:
          application/json:
            example:
              message: Bad currency

  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Invoice
        488:
          body:
            application/json:
              example:
                message: invoice not found for customer XXX
